server:
  port: 10003
spring:
  application:
    name: store-center-service
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_store?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 5  # 初始化大小
      max-wait: 60000 # 最大
      min-idle: 1 # 最小
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000   # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
  security:
    user:
      password: 123123
      name: lcw
  #zipkin-server地址
  zipkin:
    base-url: http://www.lancaiwu.com:9411/
  #接口默认全部采样
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://lcw:123123@127.0.0.1:10001/eureka/
  instance:
    appname: store-center-service
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    status-page-url:
#      http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
logging:
  config: classpath:logback.xml
#开启熔断器
feign:
  hystrix:
    enabled: true
# 开放监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS