server:
  port: 11000
spring:
  application:
    name: limit-hystrix-dashboard-turbine
eureka:
  client:
    service-url:
      defaultZone: http://lcw:123123@127.0.0.1:10001/eureka/
  instance:
    appname: limit-hystrix-dashboard-turbine
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
turbine:
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  app-config: user-center-service,store-center-service
  instanceUrlSuffix: /hystrix.stream
# 开放监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
