server:
  port: 11000
spring:
  application:
    name: limit-hystrix-dashboard-turbine
eureka:
  client:
    service-url:
      defaultZone: http://lcw:123123@127.0.0.1:10001/eureka/
  instance:
    appname: limit-hystrix-dashboard-turbine
    prefer-ip-address: true
    # ${spring.cloud.client.ip-address} \u800C\u4E0D\u662F ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
turbine:
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  app-config: user-center-service,store-center-service
  instanceUrlSuffix: /hystrix.stream  #\u6CA1\u6709\u7684\u8BDD\u4F1A\u51FA\u73B0\u5F02\u5E38\uFF0C\u627E\u4E0D\u5230\u88AB\u76D1\u63A7\u8005