server:
  port: 10004

# sentinel dashboard
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  application:
    name: limit-sentinel
# 开放监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS