server:
  port: 7970
spring:
  application:
    name: tx-manager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8
    username: root
    password: 123456

  # redis \u7684\u8BBE\u7F6E\u4FE1\u606F. \u7EBF\u4E0A\u8BF7\u7528Redis Cluster
  #redis \u4E3B\u673A
  redis:
    host: lancaiwu.cn
    #redis \u7AEF\u53E3
    port: 9736
    #redis \u5BC6\u7801
    password: '123456qq.!@#QWEE'
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  # \u5F00\u542F\u65E5\u5FD7 ,\u9ED8\u8BA4\u4E3Afalse
tx-lcn:
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
logging:
  level:
    com.codingapi: debug
